package com.gwppcore.gthandler;


import com.gwppcore.gthandler.GT_CoreModSupport;
import cpw.mods.fml.common.Loader;
import gregtech.GT_Mod;
import gregtech.api.GregTech_API;
import gregtech.api.enums.GT_Values;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.SubTag;
import gregtech.api.util.GT_ModHandler;
import gregtech.api.util.GT_OreDictUnificator;
import gregtech.api.util.GT_Utility;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

public class GT_MachineRecipeLoader implements Runnable{
	@Override
    public void run(){

/*============= CORE ITEMS CRAFTING =============*/
        //Redstone Chips
/*Ruby*/    GT_Values.RA.addLaserEngraverRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Redstone, 1L),  GT_Utility.copyAmount(0, GT_OreDictUnificator.get(OrePrefixes.lens, Materials.Ruby, 1)), CustomItemList.RedstoneRedChipset.get(1L), 50, 120, false);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.EnderPearl, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstonePulsatingChipset.get(2L), 200, 120);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.NetherQuartz, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstoneQuartzChipset.get(1L), 300, 120);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Iron, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstoneIronChipset.get(1L), 100, 120);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Gold, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstoneGoldChipset.get(1L), 200, 120);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Diamond, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstoneDiamondChipset.get(1L), 100, 480);
        GT_Values.RA.addFormingPressRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Emerald, 1L), CustomItemList.RedstoneRedChipset.get(1L), CustomItemList.RedstoneEmeraldChipset.get(1L), 150, 480);

/*============= SPARTAK CORE ITEMS CRAFTING =============*/

        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.PhobosStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BandedIron, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Bauxite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Molybdenite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Desh, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Plutonium, 1L), new int[]{5000, 2500, 1000, 750, 500, 150}, 600, 60);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.DeimosStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, Materials.SulfuricAcid.getFluid(50L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Magnesite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Pitchblende, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Cooperite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neodymium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Tungstate, 1L), new int[]{5000, 3000, 1000, 750, 650, 350}, 600, 60);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.CeresStoneDust", 1L, 0),       GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.MeteoricIron, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Beryllium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Platinum, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Titanium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Tungsten, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 2500, 1000, 750, 500, 150}, 800, 120);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.EuropaIceDust", 1L, 0),        GT_Values.NI, GT_Values.NF, Materials.Oxygen.getGas(50L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ledox, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lazurite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Mithril, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Barium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 2500, 1250, 750, 500, 150}, 800, 120);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.EuropaStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, Materials.Nitrogen.getGas(100L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.SiliconDioxide, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iron, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ledox, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Sodalite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Barium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1L), new int[]{5000, 3000, 1000, 750, 500, 300}, 800, 120);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.GanymedStoneDust", 1L, 0),     GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Titanium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chromite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Galena, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Diamond, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Palladium, 1L), new int[]{5000, 3000, 1000, 750, 600, 250}, 800, 120);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.CallistoStoneDust", 1L, 0),    GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_ModHandler.getModItem("spartakcore", "item.CallistoIceDust", 1L, 0), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Galena, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Topaz, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlueTopaz, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Lithium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Tungsten, 1L), new int[]{1500, 3000, 1000, 900, 750, 250}, 800, 120);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.IoStoneDust", 1L, 0),          GT_Values.NI, GT_Values.NF, Materials.SulfuricGas.getGas(100L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Sulfur, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tantalite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Ruby, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Gold, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Iridium, 1L), new int[]{5000, 3000, 1000, 750, 500, 250}, 1000, 256);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.VenusStoneDust", 1L, 0),       GT_Values.NI, GT_Values.NF, Materials.CarbonDioxide.getGas(500L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Carbon, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Scheelite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NiobiumNitride, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Amethyst, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Mithril, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Mithril, 1L), new int[]{10000, 3000, 1000, 750, 500, 250}, 1000, 256);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.MercuryStoneDust", 1L, 0),     GT_Values.NI, GT_Values.NF, Materials.Helium_3.getGas(50L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Vanadium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungstate, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Mithril, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Titanium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Ruby, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Diamond, 1L), new int[]{5000, 3000, 1000, 750, 500, 250}, 1000, 256);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.MercuryCoreDust", 1L, 0),      GT_Values.NI, GT_Values.NF, Materials.Helium.getGas(250L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ilmenite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungstate, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Mithril, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Titanium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Ruby, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Diamond, 1L), new int[]{5000, 3000, 1000, 750, 500, 250}, 1000, 256);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.EnceladusIceDust", 1L, 0),     GT_Values.NI, GT_Values.NF, Materials.Oxygen.getGas(150L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.MysteriousCrystal, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chrome, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Ledox, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny,  GT_CoreModSupport.Trinium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 3000, 1000, 750, 400, 200}, 1200, 480);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.EnceladusStoneDust", 1L, 0),   GT_Values.NI, GT_Values.NF, Materials.Nitrogen.getGas(150L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chrome, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Opal, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny,  GT_CoreModSupport.Trinium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 3000, 1000, 750, 400, 100}, 1200, 480);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.TitanStoneDust", 1L, 0),       GT_Values.NI, GT_Values.NF, Materials.Methane.getGas(100L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Nickel, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Emerald, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Gallium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny,  GT_CoreModSupport.Trinium, 1L), new int[]{5000, 2500, 1000, 900, 500, 200}, 1200, 480);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.OberonStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, Materials.Argon.getGas(50L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium235, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Plutonium241, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, GT_CoreModSupport.Trinium, 1L), new int[]{4000, 2000, 800, 300, 150, 150}, 1200, 480);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.MirandaStoneDust", 1L, 0),     GT_Values.NI, GT_Values.NF, Materials.Argon.getGas(50L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tin, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Desh, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Chrome, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Osmium, 1L), new int[]{4000, 2000, 1000, 750, 500, 350}, 1200, 480);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.TritonStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neodymium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.RareEarth, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Niobium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Yttrium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Gallium, 1L), new int[]{5000, 3000, 1000, 750, 500, 350}, 1400, 1024);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.ProteusStoneDust", 1L, 0),     GT_Values.NI, GT_Values.NF, Materials.Radon.getGas(10L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Copper, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uraninite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Diamond, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Plutonium, 1L), new int[]{5000, 2500, 1000, 750, 500, 350}, 1400, 1024);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),         GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Ledox, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 2500, 1250, 750, 500, 400}, 1600, 1920);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.PlutoStoneDust", 1L, 0),       GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.GarnetRed, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.GarnetYellow, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadah, 1L), new int[]{5000, 2500, 850, 500, 500, 300}, 1600, 1920);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.MakeMakeStoneDust", 1L, 0),    GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetRed, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetYellow, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Gallium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Yttrium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Niobium, 1L), new int[]{2500, 2500, 1000, 750, 500, 350}, 1600, 1920);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.HaumeaStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Lanthanum, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Caesium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Cerium, 1L), new int[]{5000, 2500, 850, 750, 500, 450}, 1600, 1920);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.CentauriASurfaceDust", 1L, 0), GT_Values.NI, GT_Values.NF, Materials.Mercury.getFluid(100L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NaquadahEnriched, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Iridium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.InfinityCatalyst, 1L), new int[]{5000, 3000, 1000, 1000, 100, 50}, 1800, 4096);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.CentauriAStoneDust", 1L, 0),   GT_Values.NI, GT_Values.NF, Materials.Mercury.getFluid(200L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NaquadahEnriched, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neutronium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.InfinityCatalyst, 1L), new int[]{5000, 2000, 500, 2500, 150, 80}, 1800, 4096);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.VegaBStoneDust", 1L, 0),       GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium235, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium241, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Europium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neutronium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Naquadria, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.DraconiumAwakened, 1L), new int[]{5000, 3000, 1500, 800, 500, 50}, 1800, 4096);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.BarnardaEStoneDust", 1L, 0),   GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neutronium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neutronium, 1L), new int[]{2500, 2000, 1500, 750, 250, 250}, 1800, 4096);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.BarnardaFStoneDust", 1L, 0),   GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neutronium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Neutronium, 1L), new int[]{2500, 2000, 1500, 750, 250, 250}, 1800, 4096);
        GT_Values.RA.addCentrifugeRecipe(GT_ModHandler.getModItem("spartakcore", "item.TCetiEStoneDust", 1L, 0),      GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Apatite, 1L), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Draconium, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.InfinityCatalyst, 1L), GT_OreDictUnificator.get(OrePrefixes.dustTiny,  GT_CoreModSupport.Trinium, 1L), new int[]{5000, 2500, 1000, 750, 150, 50}, 1800, 4096);

	    GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "phobosblocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PhobosStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BandedIron, 1)}, new int[]{10000, 5000}, 400, 64);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "phobosblocks", 1L, 1),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PhobosStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BandedIron, 1)}, new int[]{10000, 5000}, 400, 64);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "phobosblocks", 1L, 2),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PhobosStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BandedIron, 1)}, new int[]{10000, 5000}, 400, 64);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "deimosblocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.DeimosStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Magnesite, 1)}, new int[]{10000, 5000}, 400, 64);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "deimosblocks", 1L, 1),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.DeimosStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Magnesite, 1)}, new int[]{10000, 5000}, 400, 64);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ceresblocks", 1L, 0),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CeresStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.MeteoricIron, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Beryllium, 1)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ceresblocks", 1L, 1),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CeresStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.MeteoricIron, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Beryllium, 1)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "europagrunt", 1L, 1),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EuropaIceDust", 1L, 0),             GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ledox, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "europaunderwatergeyser", 1L, 0),      new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EuropaIceDust", 2L, 0),             GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ledox, 2), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 2)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "europagrunt", 1L, 0),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EuropaStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.SiliconDioxide, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iron, 1)}, new int[]{10000, 5000, 2000}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "europageyser", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EuropaStoneDust", 2L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.SiliconDioxide, 2), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iron, 2)}, new int[]{10000, 5000, 3500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ganymedeblocks", 1L, 0),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.GanymedStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Titanium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chromite, 1)}, new int[]{10000, 3500, 1000}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ganymedeblocks", 1L, 1),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.GanymedStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Titanium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chromite, 1)}, new int[]{10000, 3500, 1000}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "callistoblocks", 1L, 0),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CallistoStoneDust", 1L, 0),         GT_ModHandler.getModItem("spartakcore", "item.CallistoIceDust", 1L, 0), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Galena, 1)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "callistoblocks", 1L, 1),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CallistoStoneDust", 1L, 0),         GT_ModHandler.getModItem("spartakcore", "item.CallistoIceDust", 1L, 0), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Galena, 1)}, new int[]{10000, 5000, 2500}, 400, 120);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ioblocks", 1L, 0),                    new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.IoStoneDust", 1L, 0),               GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Sulfur, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tantalite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1)}, new int[]{10000, 5000, 2500, 1500}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ioblocks", 1L, 1),                    new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.IoStoneDust", 1L, 0),               GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ash, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Sulfur, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tantalite, 1)}, new int[]{10000, 5000, 3000, 2000}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "ioblocks", 1L, 2),                    new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.IoStoneDust", 1L, 0),               GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Sulfur, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tantalite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1)}, new int[]{10000, 5000, 2500, 1500}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "venusblocks", 1L, 0),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.VenusStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Scheelite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NiobiumNitride, 1)}, new int[]{10000, 4500, 2500, 1500}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "venusblocks", 1L, 1),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.VenusStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Scheelite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NiobiumNitride, 1)}, new int[]{10000, 4500, 2500, 1500}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mercuryblocks", 1L, 0),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MercuryStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ilmenite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Mithril, 1)}, new int[]{10000, 3000, 2000, 1200}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mercuryblocks", 1L, 1),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MercuryStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ilmenite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Mithril, 1)}, new int[]{10000, 3000, 2000, 1200}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mercuryblocks", 1L, 2),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MercuryCoreDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Ilmenite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tungsten, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Mithril, 1)}, new int[]{10000, 3000, 2000, 1200}, 400, 256);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "enceladusblocks", 1L, 0),             new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EnceladusIceDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.MysteriousCrystal,1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chrome, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1)}, new int[]{10000, 1500, 2000, 1000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "enceladusblocks", 1L, 1),             new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.EnceladusStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Chrome, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1)}, new int[]{10000, 3000, 2000, 1000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "titanblocks", 1L, 0),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TitanStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Nickel, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1)}, new int[]{10000, 4500, 3000, 2000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "titanblocks", 1L, 1),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TitanStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Nickel, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1)}, new int[]{10000, 4500, 3000, 2000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "titanblocks", 1L, 2),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TitanStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Nickel, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1)}, new int[]{10000, 4500, 3000, 2000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "oberonblocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.OberonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1)}, new int[]{10000, 2000, 1000, 850}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "oberonblocks", 1L, 1),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.OberonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1)}, new int[]{10000, 2000, 1000, 850}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "oberonblocks", 1L, 2),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.OberonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1)}, new int[]{10000, 2000, 1000, 850}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mirandablocks", 1L, 0),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MirandaStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tin, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1)}, new int[]{10000, 2500, 1500, 1000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mirandablocks", 1L, 1),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MirandaStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tin, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1)}, new int[]{10000, 2500, 1500, 1000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "mirandablocks", 1L, 2),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MirandaStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tin, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Tetrahedrite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1)}, new int[]{10000, 2500, 1500, 1000}, 400, 480);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "proteusblocks", 1L, 0),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.ProteusStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Copper, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uraninite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "proteusblocks", 1L, 1),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.ProteusStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Copper, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uraninite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "proteusblocks", 1L, 2),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.ProteusStoneDust", 1L, 0),          GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Copper, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uraninite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tritonblocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TritonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neodymium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.RareEarth, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tritonblocks", 1L, 1),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TritonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neodymium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.RareEarth, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tritonblocks", 1L, 2),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TritonStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neodymium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.RareEarth, 1)}, new int[]{10000, 5000, 2500, 1000}, 400, 1024);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 0),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),              GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1)}, new int[]{10000, 5000, 2500, 1250}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 1),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),              GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1)}, new int[]{10000, 5000, 2500, 1250}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 2),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),              GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1)}, new int[]{10000, 5000, 2500, 1250}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 3),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),              GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1)}, new int[]{10000, 5000, 2500, 1250}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 4),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoIceDust", 1L, 0),              GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Thorium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1)}, new int[]{10000, 5000, 2500, 1250}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "plutoblocks", 1L, 5),                 new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.PlutoStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 5000, 2500, 850}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "makemakegrunt", 1L, 0),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MakeMakeStoneDust", 1L, 0),         GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetRed, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetYellow, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 2500, 2500, 1000}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "makemakegrunt", 1L, 1),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.MakeMakeStoneDust", 1L, 0),         GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetRed, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.GarnetYellow, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 2500, 2500, 1000}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "haumeablocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.HaumeaStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gold, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Naquadah, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1)}, new int[]{10000, 5000, 2500, 850}, 400, 1920);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "acentauribbgrunt", 1L, 0),            new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CentauriASurfaceDust", 1L, 0),      GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Iridium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NaquadahEnriched, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Draconium, 1)}, new int[]{10000, 5000, 3000, 1000}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "acentauribbsubgrunt", 1L, 0),         new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.CentauriAStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Osmium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.NaquadahEnriched, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neutronium, 1)}, new int[]{10000, 5000, 3000, 500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "vegabsubgrunt", 1L, 0),               new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.VegaBStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium235, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium241, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Europium, 1)}, new int[]{10000, 5000, 3000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "vegabgrunt", 1L, 0),                  new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.VegaBStoneDust", 1L, 0),            GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Uranium235, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Plutonium241, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Europium, 1)}, new int[]{10000, 5000, 3000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "barnardaEgrunt", 1L, 0),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.BarnardaEStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "barnardaEsubgrunt", 1L, 0),           new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.BarnardaEStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "barnardaFgrunt", 1L, 0),              new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.BarnardaFStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "barnardaFsubgrunt", 1L, 0),           new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.BarnardaFStoneDust", 1L, 0),        GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Gallium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Niobium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tcetieblocks", 1L, 0),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TCetiEStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Apatite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tcetieblocks", 1L, 1),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TCetiEStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Apatite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);
        GT_Values.RA.addPulveriserRecipe(GT_ModHandler.getModItem("GalaxySpace", "tcetieblocks", 1L, 2),                new ItemStack[]{GT_ModHandler.getModItem("spartakcore", "item.TCetiEStoneDust", 1L, 0),           GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lapis, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Apatite, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BlackPlutonium, 1)}, new int[]{10000, 2500, 2000, 1500}, 400, 4096);

/*============= SPACE BOX RECIPES =============*/
	//===0
	    GT_Values.RA.addChemicalBathRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Stone, 64), Materials.Glue.getFluid(1000), CustomItemList.packEarth.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 8);
	
	//===1
        GT_Values.RA.addChemicalBathRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Moon, 64), Materials.Plastic.getMolten(144L), CustomItemList.packMoon.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 20);
	
	//===2
        GT_Values.RA.addChemicalBathRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Mars, 64), Materials.PolyvinylChloride.getMolten(144L), CustomItemList.packMars.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 50);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.PhobosStoneDust", 64L, 0), Materials.PolyvinylChloride.getMolten(144L), CustomItemList.packPhobos.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 50);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.DeimosStoneDust", 64L, 0), Materials.PolyvinylChloride.getMolten(144L), CustomItemList.packDeimos.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 50);
        
	//===3
	    GT_Values.RA.addChemicalBathRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Asteroid, 64), Materials.Polystyrene.getMolten(144L), CustomItemList.packAsteroids.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 125);
	    GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.CeresStoneDust", 64L, 0), Materials.Polystyrene.getMolten(144L), CustomItemList.packCeres.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 125);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.EuropaStoneDust", 64L, 0), Materials.Polystyrene.getMolten(144L), CustomItemList.packEuropa.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 125);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.GanymedStoneDust", 64L, 0), Materials.Polystyrene.getMolten(144L), CustomItemList.packGanymed.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 125);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.CallistoStoneDust", 64L, 0), Materials.Polystyrene.getMolten(144L), CustomItemList.packCallisto.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 125);
        
	//===4
	    GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.IoStoneDust", 64L, 0), Materials.Polytetrafluoroethylene.getMolten(144L), CustomItemList.packIo.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 312);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.VenusStoneDust", 64L, 0), Materials.Polytetrafluoroethylene.getMolten(144L), CustomItemList.packVenus.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 312);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.MercuryCoreDust", 64L, 0), Materials.Polytetrafluoroethylene.getMolten(144L), CustomItemList.packMercury.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 312);
        
	//===5
	    GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.EnceladusStoneDust", 64L, 0), Materials.PolyphenyleneSulfide.getMolten(144L), CustomItemList.packIapetus.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 780);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.TitanStoneDust", 64L, 0), Materials.PolyphenyleneSulfide.getMolten(144L), CustomItemList.packTitan.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 780);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.OberonStoneDust", 64L, 0), Materials.PolyphenyleneSulfide.getMolten(144L), CustomItemList.packOberon.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 780);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.MirandaStoneDust", 64L, 0), Materials.PolyphenyleneSulfide.getMolten(144L), CustomItemList.packEris.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 780);
        
	//===6
	    GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.TritonStoneDust", 64L, 0), Materials.Polybenzimidazole.getMolten(144L), CustomItemList.packTriton.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 1950);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.ProteusStoneDust", 64L, 0), Materials.Polybenzimidazole.getMolten(144L), CustomItemList.packProteus.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 1950);
        
	//===7
	    GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.PlutoStoneDust", 64L, 0), Materials.Polybenzimidazole.getMolten(288L), CustomItemList.packPluto.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 4875);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.MakeMakeStoneDust", 64L, 0), Materials.Polybenzimidazole.getMolten(288L), CustomItemList.packMakeMake.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 4875);
        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.HaumeaStoneDust", 64L, 0), Materials.Polybenzimidazole.getMolten(288L), CustomItemList.packHaumea.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 4875);
        
	//===8
//        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.CentauriAStoneDust", 64L, 0), Materials.Radox.getMolten(144L), CustomItemList.packCentauriA.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 12188);
//        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.VegaBStoneDust", 64L, 0), Materials.Radoxpoly.getMolten(144L), CustomItemList.packVegaB.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 12188);
//        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.BarnardaEStoneDust", 64L, 0), Materials.Radoxpoly.getMolten(144L), CustomItemList.packBarnardaE.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 12188);
//        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.BarnardaFStoneDust", 64L, 0), Materials.Radoxpoly.getMolten(144L), CustomItemList.packBarnardaF.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 12188);
//        GT_Values.RA.addChemicalBathRecipe(GT_ModHandler.getModItem("spartakcore", "item.TCetiEStoneDust", 64L, 0), Materials.Radoxpoly.getMolten(144L), CustomItemList.packTCetiE.get(1L), GT_Values.NI, GT_Values.NI, new int[]{10000}, 200, 12188);
        
	}

}
