package com.impact.recipes.machines;

import com.impact.mods.GregTech.GTregister.GT_Materials;
import gregtech.api.enums.GT_Values;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.util.GT_OreDictUnificator;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;

public class BlastSmelterRecipe implements Runnable{
    @Override
    public void run(){


        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt, 1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Molybdenum, 8), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Tungsten, 1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Copper, 1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Chrome, 7), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel, 32)}, null, null, GT_Materials.HastelloyC276.getMoltenHot(144L*50), 40*20, 7680, 3666);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Niobium,23), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Tantalum,1), GT_OreDictUnificator.get(OrePrefixes.dust, GT_Materials.Zirconium,2)}, null, null, GT_Materials.GumMetal.getMoltenHot(144L*27), 40*20, 7680, 3777);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Niobium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Tantalum,1)}, null, null, GT_Materials.Titaniolum.getMoltenHot(144L*3), 40*20, 7680, 3888);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Steel,5), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Manganese,2)}, null, null, GT_Materials.Mangalloy.getMoltenHot(144L*7), 40*20, 7680, 3940);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,4), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Copper,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Magnesium,1)}, null, null, GT_Materials.Zamak.getMoltenHot(144L*8), 40*20, 7680, 3999);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Iron,5), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt,2)}, null, null, GT_Materials.Kovar.getMoltenHot(144L*10), 40*20, 7680, 4002);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 2L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Copper,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Magnesium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Manganese,1)}, null, null, GT_Materials.Duraluminium.getMoltenHot(144L*8), 40*20, 7680, 4111);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Chrome,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Niobium,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Molybdenum,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nichrome,1)}, null, null, GT_Materials.Inconel690.getMoltenHot(144L*6), 40*20, 7680, 4222);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,1)}, null, null, GT_Materials.Nitinol.getMoltenHot(144L*2), 40*20, 7680, 4333);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Niobium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nichrome,1)}, null, null, GT_Materials.Inconel792.getMoltenHot(144L*6), 40*20, 7680, 4444);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Vanadium,8), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Chrome,6), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Molybdenum,4), GT_OreDictUnificator.get(OrePrefixes.dust, GT_Materials.Zirconium,4)}, null, null, GT_Materials.TiBetaC.getMoltenHot(144L*23), 40*20, 7680, 4555);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,9), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Carbon,9), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Kalium,9), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Lithium,9), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Sulfur,9)}, null, null, GT_Materials.Grisium.getMoltenHot(144L*45), 40*20, 7680, 4601);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 2L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Steel,16), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,4), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt,2)}, null, null, GT_Materials.MaragingSteel250.getMoltenHot(144L*24), 40*20, 7680, 4666);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 1L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt,4), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Chrome,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Phosphor,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Molybdenum,1)}, null, null, GT_Materials.Talonite.getMoltenHot(144L*10), 40*20, 7680, 4770);

        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 2L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,2)}, null, null, GT_Materials.Nitinol60.getMoltenHot(144L*5), 40*20, 7680, 4701);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 3L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Steel,16), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Titanium,1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Nickel,4), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt,2)}, null, null, GT_Materials.MaragingSteel300.getMoltenHot(144L*24), 40*20, 7680, 4300);
        GT_Values.RA.addBlastSmelterRecipe(new ItemStack[] {ItemList.Circuit_Integrated.getWithDamage(0L, 2L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Chrome,3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Cobalt,7), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Phosphor,2), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Molybdenum,1)},null, null, GT_Materials.Stellite.getMoltenHot(144L*13), 40*20, 7680, 4121);

    }
}
