package com.impact.recipes;

import gregtech.api.enums.GT_Values;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.util.GT_ModHandler;
import gregtech.api.util.GT_OreDictUnificator;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import static gregtech.api.util.GT_ModHandler.*;

public class AfterGregTechPostLoadRecipes implements Runnable {
    @Override
    public void run() {

        //removeRecipe(ItemStack aInput);

        //removeFurnaceSmelting(ItemStack aInput)
        removeFurnaceSmelting(GT_ModHandler.getModItem("TConstruct", "CraftedSoil", 1L, 1));
        removeFurnaceSmelting(new ItemStack(Items.clay_ball, 1, 0));

        //removeRecipeByOutput();
        removeRecipeByOutput(GT_ModHandler.getIC2Item("nanoHelmet", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("nanoBodyarmor", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("nanoLeggings", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("nanoBoots", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("quantumHelmet", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("quantumBodyarmor", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("quantumLeggings", 1, GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getIC2Item("quantumBoots", 1, GT_Values.W));

        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "advJetpack", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "advNanoChestPlate", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "ultimateLappack", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "relocator", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "vajra", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "graviTool", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "advChainsaw", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "advDDrill", GT_Values.W));
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 7), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 6), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "itemSimpleItem", 1L, 3), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "blockTelePad", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "blockTransceiver", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockController", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockChest", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockDrive", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockCraftingUnit", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockMolecularAssembler", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockQuantumRing", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockQuantumLinkChamber", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockSpatialPylon", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockSpatialIOPort", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockInterface", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "tile.BlockEnergyAcceptor", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 500), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 260), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 240), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 220), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 460), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 140), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 35), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 36), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 37), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 38), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 32), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 33), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 34), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1L, 39), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemBasicStorageCell.1k", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemBasicStorageCell.4k", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemBasicStorageCell.16k", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemBasicStorageCell.64k", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemSpatialStorageCell.2Cubed", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemSpatialStorageCell.16Cubed", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemSpatialStorageCell.128Cubed", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemViewCell", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("appliedenergistics2", "item.ItemMultiPart", 1L, 180), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "part.base", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "part.base", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "part.base", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 3), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 6), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 7), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 8), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 9), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.component", 1L, 10), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.casing", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.casing", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 3), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.fluid", 1L, 6), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.physical", 1L), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.physical", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.physical", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("extracells", "storage.physical", 1L, 3), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "enderQuarry", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "endMarker", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "dark_portal", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("IC2", "blockGenerator", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("IC2", "blockGenerator", 1L, 9), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("IC2", "blockKineticGenerator", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("IC2", "blockKineticGenerator", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 3), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 6), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 7), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 8), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 9), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 10), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("compactkineticgenerators", "BlockCkg", 1L, 11), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "graviChestPlate", 1L, GT_Values.W), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("GraviSuite", "kpChestPlate", 1L, GT_Values.W), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockMachineManagerName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableBreakerName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableSignName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableClusterName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableClusterName", 1L, 8), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableOutputName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableInputName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableRelayName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableRelayName", 1L, 8), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableBUDName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableCamouflageName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableCamouflageName", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableCamouflageName", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableIntakeName", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("StevesFactoryManager", "BlockCableIntakeName", 1L, 8), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 15), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 3), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 4), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 5), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 11), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "logisticsSolidBlock", 1L, 12), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "item.PipeItemsBasicTransport", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "item.PipeItemsBasicLogistics", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "item.PipeFluidBasic", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("LogisticsPipes", "item.PipeBlockRequestTable", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "blockInventoryPanel", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "itemFunctionUpgrade", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "itemItemConduit", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "itemLiquidConduit", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("EnderIO", "itemYetaWrench", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("StorageDrawers", "controller", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "crafting_table", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "chest", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "trapped_chest", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "dispenser", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "dropper", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "sticky_piston", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "rail", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "golden_rail", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "detector_rail", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "activator_rail", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "noteblock", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "jukebox", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "trapdoor", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "stone_pressure_plate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "wooden_pressure_plate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "glass_pane", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "torch", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "fence", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "fence_gate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "tripwire_hook", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "anvil", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "wooden_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "iron_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_sword", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_shovel", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_pickaxe", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_axe", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_hoe", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_helmet", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_chestplate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_leggings", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "diamond_boots", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "saddle", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "item_frame", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "bed", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "fishing_rod", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "ladder", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "stone_pressure_plate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "wooden_pressure_plate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "enchanting_table", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("minecraft", "brewing_stand", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "iron_trapdoor", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "sliding_trapdoor", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "player_sensor", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "vanishing_block", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "vanishing_block", 1L, 1), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "vanishing_block", 1L, 2), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "vanishing_block", 1L, 3), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "block_mixer", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "door_factory", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "rustyHatch", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "garage_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.rustyHandle", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "rustyLadder", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.door_acacia", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.door_birch", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.door_dark_oak", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.door_jungle", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.door_spruce", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.wood_sliding_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.iron_sliding_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.jail_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.laboratory_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.factory_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.shoji_door", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_purple", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_yellow", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_magenta", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_pink", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_white", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_blue", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_gray", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_cyan", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_red", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_brown", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_lime", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_orange", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_silver", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_green", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_light_blue", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.curtain_black", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.saloon", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "item.forcefieldItem", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "acaciaFenceGate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "birchFenceGate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "darkOakFenceGate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "jungleFenceGate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "spruceFenceGate", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "trapdoor_acacia", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "trapdoor_birch", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "trapdoor_dark_oak", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "trapdoor_jungle", 1L, 0), true, false, false);
        removeRecipeByOutput(GT_ModHandler.getModItem("malisisdoors", "trapdoor_spruce", 1L, 0), true, false, false);

        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersBlock", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersCollapsibleBlock", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "itemCarpentersChisel", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "itemCarpentersHammer", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersSafe", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersDaylightSensor", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "itemCarpentersBed", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersTorch", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersGarageDoor", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersLadder", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersBarrier", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersPressurePlate", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersButton", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersFlowerPot", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersGate", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersHatch", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersLever", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersSlope", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "blockCarpentersStairs", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "itemCarpentersTile", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("CarpentersBlocks", "itemCarpentersDoor", 1, 0), true, false, true);

        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "dark_portal", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "enderThermicPump", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "chestMini", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "chestFull", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "trashcan", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "watering_can", 1, 1), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "timer", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "angelBlock", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "golden_bag", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 4), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 5), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 3), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 7), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 8), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 1), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 2), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 6), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 9), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 10), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock2", 1, 11), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 9), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 4), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 7), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 6), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 3), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 10), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ExtraUtilities", "decorativeBlock1", 1, 13), true, false, true);

        removeRecipeByOutput(GT_ModHandler.getModItem("ArchitectureCraft", "sawbench", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ArchitectureCraft", "sawblade", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ArchitectureCraft", "largePulley", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ArchitectureCraft", "hammer", 1, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ArchitectureCraft", "chisel", 1, 0), true, false, true);

        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "Printing Press", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioChase", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "Typesetting Machine", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "tile.BiblioframeGtdChest", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioPaintPress", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioLantern", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioIronLantern", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioLamp", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioIronLamp", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "Armor Stand", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioBell", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioStuffs", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "BiblioStuffs", 1L, 2), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.FramingSaw", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.FramingSheet", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.FramingBoard", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioMapTool", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioWayPointCompass", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioGlasses", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioGlasses", 1L, 2), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.PlumbLine", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.HandDrill", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioDrill", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.tape", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.tapeMeasure", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.BiblioClipboard", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.SlottedBook", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("BiblioCraft", "item.AtlasBook", 1L, 0), true, false, true);

        removeRecipeByOutput(GT_ModHandler.getModItem("ae2stuff", "Wireless", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ae2stuff", "WirelessKit", 1L, 0), true, false, true);
        removeRecipeByOutput(GT_ModHandler.getModItem("ae2stuff", "Visualiser", 1L, 0), true, false, true);

        removeRecipeByOutput(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.CokeCoal, 1), true, false, false);
    }
}
